pipeline:
    docker:
      when:
        branch:
          - master
        event:
          - push
      secrets: [docker_username, docker_password]
      image: plugins/docker
      repo: helenbelen111/reelapp
      context: reelapp-video-watch
      Dockerfile: reelapp-video-watch/Dockerfile
