pipeline:
    docker:
      when:
        event:
          - push
        branch:
          - master

      secrets: [docker_username, docker_password]
      image: plugins/docker
      repo: helenbelen111/reelapp
      context: reelapp-source
      Dockerfile: reelapp-video-watch/Dockerfile
